services:
    ortofit_quiz.simple_state_factory:
        class: Ortofit\Bundle\QuizBundle\Factory\State\SimpleStateFactory
        arguments: [@templating.engine.twig]

    ortofit_quiz.flow_manager:
        class: Ortofit\Bundle\QuizBundle\Flow\FlowManager
        arguments: [@ortofit_quiz.simple_state_factory]

    ortofit_quiz.result_manager:
        class: Ortofit\Bundle\QuizBundle\Result\ResultManager
        arguments: [@doctrine.orm.entity_manager]