admin_panel:
    path:     /admin
    defaults: { _controller: OrtofitBackOfficeBundle:Default:index }
login_route:
    path:     /login
    defaults: { _controller: OrtofitBackOfficeBundle:Login:login }
logout:
    path:     /admin/logout
    defaults: { _controller: OrtofitBackOfficeBundle:Login::logout }
login_check:
    path:     /admin/login_check
    defaults: { _controller: OrtofitBackOfficeBundle:Login:securityCheck }
backend_manage_get:
    path:     /admin/get/{object}
    defaults: { _controller: OrtofitBackOfficeBundle:Manage:get }
backend_manage_create:
    path:     /admin/get/{object}
    defaults: { _controller: OrtofitBackOfficeBundle:Manage:create }
backend_manage_update:
    path:     /admin/get/{object}
    defaults: { _controller: OrtofitBackOfficeBundle:Manage:update }
backend_manage_remove:
    path:     /admin/get/{object}
    defaults: { _controller: OrtofitBackOfficeBundle:Manage:remove }