ortofit_sing_up_index:
    path:     /sing_up/index/{countryIso2}
    defaults: { _controller: OrtofitSingUpBundle:SingUp:index }

ortofit_sing_up_add:
    path:     /sing_up/post
    defaults: { _controller: OrtofitSingUpBundle:SingUp:post }