services:
#    ortofit_sing_up.example:
#        class: Ortofit\Bundle\SingUpBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    ortofit_sing_up.client_manager:
        class: Ortofit\Bundle\SingUpBundle\Service\ClientManager
        arguments: [@doctrine.orm.entity_manager]

    ortofit_sing_up.application_manager:
        class: Ortofit\Bundle\SingUpBundle\Service\ApplicationManager
        arguments: [@doctrine.orm.entity_manager]

    ortofit_sing_up.order_manager:
        class: Ortofit\Bundle\SingUpBundle\Service\OrderManager
        arguments: [@doctrine.orm.entity_manager]

    ortofit_sing_up.application_flow:
        class: Ortofit\Bundle\SingUpBundle\Application\ApplicationFlow
        arguments: [@ortofit_sing_up.order_manager, @ortofit_sing_up.client_manager]
        calls:
            - [setTemplateEngine, [@templating.engine.twig]]
            - [setSession, [@session]]
